name: ios

on:
  workflow_dispatch:
    inputs:
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:

  build-lib-ios:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly

      - name: install toolchain
        run: |
          rustup target add aarch64-apple-ios
          cargo install cargo-lipo
          cargo install cbindgen
          brew uninstall openssl@1.0.2t
          brew uninstall python@2.7.17
          brew untap local/openssl
          brew untap local/python2
          brew update && brew install llvm unzip protobuf

      - name: build
        run: |
          # OPENSSL_DIR=/tmp/openssl-ios64 cargo lipo --release -p leaf-mobile --targets aarch64-apple-ios
          make ios

      - name: zip artifacts
        run: |
          mv target/universal/release/libleaf.a .
          mv target/universal/release/leaf.h .
          zip libleaf-ios.zip leaf.h libleaf.a

      - name: upload assets
        uses: actions/upload-artifact@v2
        with:
          name: libleaf-ios.zip
          path: libleaf-ios.zip

  